// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiW9q7B6xm0Yhv_KdUPoMAXuo4jpN1gfI',
    appId: '1:295643787744:web:715bbc9165b73eef3bbb85',
    messagingSenderId: '295643787744',
    projectId: 'not-app-76980',
    authDomain: 'not-app-76980.firebaseapp.com',
    storageBucket: 'not-app-76980.firebasestorage.app',
    measurementId: 'G-VBGCX8VYNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6f4H2_-wY7Tmew41ty_ti7tbNI6oH7Q8',
    appId: '1:295643787744:android:c212a609e23ddd233bbb85',
    messagingSenderId: '295643787744',
    projectId: 'not-app-76980',
    storageBucket: 'not-app-76980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAUxtbs6ZIZ4rABXkK838cULi9QpGDn44',
    appId: '1:295643787744:ios:592fff440f862d283bbb85',
    messagingSenderId: '295643787744',
    projectId: 'not-app-76980',
    storageBucket: 'not-app-76980.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAUxtbs6ZIZ4rABXkK838cULi9QpGDn44',
    appId: '1:295643787744:ios:592fff440f862d283bbb85',
    messagingSenderId: '295643787744',
    projectId: 'not-app-76980',
    storageBucket: 'not-app-76980.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiW9q7B6xm0Yhv_KdUPoMAXuo4jpN1gfI',
    appId: '1:295643787744:web:e9451bb826aeb2293bbb85',
    messagingSenderId: '295643787744',
    projectId: 'not-app-76980',
    authDomain: 'not-app-76980.firebaseapp.com',
    storageBucket: 'not-app-76980.firebasestorage.app',
    measurementId: 'G-C442FNBVMG',
  );
}
